[package]
name = "repo-intelligence-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
regex.workspace = true
repo-intelligence-config = { path = "../config" }
repo-intelligence-embedding = { path = "../embedding" }
repo-intelligence-graph = { path = "../graph" }
repo-intelligence-model = { path = "../model" }
repo-intelligence-parsing = { path = "../parsing" }
repo-intelligence-semantics = { path = "../semantics" }
repo-intelligence-source = { path = "../source" }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

