[package]
name = "repo-intelligence-semantics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
regex.workspace = true
repo-intelligence-config = { path = "../config" }
repo-intelligence-model = { path = "../model" }
repo-intelligence-parsing = { path = "../parsing" }
repo-intelligence-source = { path = "../source" }
serde_json.workspace = true
tree-sitter.workspace = true
